### ISSUE TITLE
Allow for date format change

### ISSUE THREAD

**Issue by y0nm4n** [alecgorge/PhishOD-iOS#107]
I'm on an iPhone 5s, and I can only see the year and month + venue for shows. This is rather frustrating as seeing the day of the month is pretty important when choosing shows based on dates. Perhaps you could allow for customizing the date format so that I could see DD/MM/YY instead of YYYY/MM/DD. For view by year mode why would I need to see the year anyway?

Great app which would be perfect with this slight fix

**Comment by alecgorge** [comment]
That's a bug with PhishOD and iOS 9. I have fixed this bug and submitted it to Apple several times, but PhishOD keeps being rejected on legal grounds that I don't have the rights to offer downloads of songs which if very frustrating because I do but Apple doesn't accept the tapers policy as sufficient evidence...

In the meantime you can use Relisten. It doesn't have the same issue but it doesn't have all the Phish specific info

**Comment by y0nm4n** [comment]
That's frustrating. Apple can suck sometimes. Thanks for the app!
See you on tour :)






On Tue, Feb 9, 2016 at 10:30 AM -0800, "Alec Gorge" <notifications@github.com> wrote:












That's a bug with PhishOD and iOS 9. I have fixed this bug and submitted it to Apple several times, but PhishOD keeps being rejected on legal grounds that I don't have the rights to offer downloads of songs which if very frustrating because I do but Apple doesn't accept the tapers policy as sufficient evidence...



In the meantime you can use Relisten. It doesn't have the same issue but it doesn't have all the Phish specific info
