### ISSUE TITLE
Question: where can I get API of "phishtrackstats.com"?

### ISSUE THREAD

**Issue by inix** [alecgorge/PhishOD-iOS#80]
I notice that this APP use APIs from site "phishtrackstats.com" to get heatmaps.json for example,but I can not found any API docs posted on this website.

Does it private and not public yet?or,do it provided by third party site?

Thanks

**Comment by alexebird** [comment]
Those apis are provided by my site, phishtrackstats.com. It's public but
undocumented since nobody has wanted to know anything about it until now.
If you want to use it I will make you an api key and write up some docs.
I'm happy to answer any questions about it. Thanks!

**Comment by inix** [comment]
> Those apis are provided by my site, phishtrackstats.com. It's public but
> undocumented since nobody has wanted to know anything about it until now.
> If you want to use it I will make you an api key and write up some docs.
> I'm happy to answer any questions about it. Thanks!

I am learning this APP's source code and try to write some extension for studying.It will be nice that you help writing some docs about those API.

Thanks a lot!

**Comment by alexebird** [comment]
Hey @inix, sorry about the long delay. I don't really have a good excuse, but I hope you're still interested in the API! I've tried to keep the API clean and nice, but since I've been the only one developing with it there might be some inconsistencies or things that seem just plain stupid.

Email me at alexebird@gmail.com if you still want an API key.

Here's some basic info about the API:

* api/v1 is no longer supported (i'm pretty sure)
* api/v2 requires the `Authorization` header to be set. The value should be `Basic base64encode(api_key:[session_key])`, where the base64encode part is an actual base64 string. `session_key` is optional, but the colon is always required.
* Set `Content-Type` header to `application/json` when passing a request with a JSON body.
* All api/v2 URLs should start with `https://www.phishtrackstats.com/api/v2/`. For example, `https://www.phishtrackstats.com/api/v2/ping2.json`.
* To test out that you're hitting the API successfully, try these:
    
```bash
# /ping.json - only api key required
$ curl -XGET -H "Authorization: Basic $(echo 'API_KEY:' | base64)" https://www.phishtrackstats.com/api/v2/ping.json

# /ping2.json - api key and session key required
$ curl -XGET -H "Authorization: Basic $(echo 'API_KEY:SESSION_KEY' | base64)" https://www.phishtrackstats.com/api/v2/ping2.json

# /ping3.json - no api key or session key required
$ curl -XGET https://www.phishtrackstats.com/api/v2/ping3.json
```

Once that's working you can start hitting more interesting endpoints:

```bash
# create a session to get a session_key
$ curl -XPOST -H"Authorization: Basic XYZ" -H"Content-Type: application/json" -d'
{
    "login": "bogus",
    "password": "asdfasdf" 
}' https://www.phishtrackstats.com/api/v2/sessions.json

# post a play -- please use test_mode: true when appropriate so as not to
# affect production play data...accurate play data is the whole point of this project.
$ curl -XPOST -H"Authorization: Basic XYZ" -H"Content-Type: application/json" -d'
{ "play_event": {
    "track_id": 28737,
    "streaming_site": "phishin"},
  "test_mode": true
}' https://www.phishtrackstats.com/api/v2/plays.json

# get some stats
$ curl -XPOST -H"Authorization: Basic XYZ" -H"Content-Type: application/json" -d'
{
  "stats_query": {
	"entity": "tracks",
    "filters": [{"attr_name": "track_title", "operator": "in", "attr_value": ["carini","tweezer"]},
                {"attr_name": "year", "operator": "gte", "attr_value": 2013}],
    //"filters": [{"attr_name": "track_duration", "operator": "gte", "attr_value": 1200000}],
	"timeframe": "all_time",
    //"timeframe": { "start": "2014-01-01T10:56:00", "end": "2014-01-05T15:12:00" },
    "timezone": "Central Time (US & Canada)",
	"stats": [ // I'm pretty sure this key ignores the value and gives you predetermined stats
		{ "name": "play_count" },
		{ "name": "unique_count" },
      	{ "name": "duration_sum_fmt" },
      	{ "name": "duration_sum_sec" },
      	{ "name": "catalog_progress" },
      	{ "name": "total_count" },
		{ "name": "play_count_ranking", "limit": 10, "offset": 0 }
	]
  }
}' https://www.phishtrackstats.com/api/v2/plays/stats.json
# or get a user's stats with the endpoint /api/v2/users/:user_id/plays/stats.json and the same query json

# get a list of recent plays
$ curl -XGET -H"Authorization: Basic XYZ" https://www.phishtrackstats.com/api/v2/plays.json?limit=3&offset=0

# get a heatmap
$ curl -XPOST -H"Authorization: Basic XYZ" -H"Content-Type: application/json" -d'
{
  "heatmap_query": {
	"entity": "show",
    "filter": "2013-07-31",
    // this style of time frame also works for stats queries
    "timeframe": { "start": "2014-01-01T10:56:00", "end": "2014-01-05T15:12:00" },
    "timezone": "Central Time (US & Canada)"
  }
}' https://www.phishtrackstats.com/api/v2/plays/heatmaps.json
```

Good luck and let me know if you have any questions!

**Comment by inix** [comment]
hi,@alexebird,Thanks a lot.This is a lot useful for me,I am studying carefully this project codes.
